server:
  port: 9988
  tomcat:
    basedir: .
    accesslog:
      directory: ./logs
      enabled: true
      pattern: "%{YYYY-MM-dd HH:mm:ss}t %{X-Request-Id}o %h \"%r\" %s %b %D"
      file-date-format: ""
      request-attributes-enabled: true
spring:
  datasource:
    url: jdbc:mysql://172.21.188.234:3306/dq_refuse_classification?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: super
    password: Alibaba_1688
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.citydo.lcl.domain
logs:
  file: logs/
